apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-core-backend-from-frontend
  namespace: otel-demo
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - cart
          - checkout
          - product-catalog
          - recommendation
          - payment
          - shipping
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: frontend
      ports:
        - protocol: TCP
          port: 8080