apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: otel-demo
spec:
  # 1. target which service to scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  
  # 2. scale range
  minReplicas: 1
  maxReplicas: 10
  
  # 3. target CPU utilization percentage
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50