apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-credentials
  namespace: otel-demo
spec:
  provider: aws
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: db-username
          key: username
        - objectName: db-password
          key: password
        - objectName: db-connection
          key: connectionString
  parameters:
    objects: |
      - objectName: "otel-demo/rds/app-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
      - objectName: "otel-demo/rds/connection-string"
        objectType: "secretsmanager"
        jmesPath:
          - path: "connectionString"
            objectAlias: "db-connection"

