apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-credentials
  namespace: otel-demo
spec:
  provider: aws
  secretObjects:
    - secretName: grafana-admin
      type: Opaque
      data:
        - objectName: admin-credentials-username
          key: admin-user
        - objectName: admin-credentials-password
          key: admin-password
  parameters:
    objects: |
      - objectName: "otel-demo/grafana/admin-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: admin-credentials-username
          - path: password
            objectAlias: admin-credentials-password

